// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdi4Hza81Zbb5Ak8yvgZc2bd4Pa85ZOG8',
    appId: '1:517307621575:web:b7c338013fef01da95dee2',
    messagingSenderId: '517307621575',
    projectId: 'glozer-project',
    authDomain: 'glozer-project.firebaseapp.com',
    storageBucket: 'glozer-project.firebasestorage.app',
    measurementId: 'G-E09M8S66MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfc-sI0Bcg5fM8GLtP5wGi3Hdn7Clkgw',
    appId: '1:517307621575:android:67af8ea50112464595dee2',
    messagingSenderId: '517307621575',
    projectId: 'glozer-project',
    storageBucket: 'glozer-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sYO1Uqy5_nelpPUiv0ujOQoq8O-QF5o',
    appId: '1:517307621575:ios:22ac803d4a5c9a4395dee2',
    messagingSenderId: '517307621575',
    projectId: 'glozer-project',
    storageBucket: 'glozer-project.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );
}
